2020-05-01 21:39:03,508 ERROR: Exception on /index [GET] [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\main\routes.py", line 39, in index
    prev_url=prev_url)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\templates\base.html", line 22, in template
    <li><a href="{{ url_for(https://www.facebook.com/) }}">{{ _('Follow us') }}</a></li>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got ':'
2020-05-01 21:39:09,541 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:40:43,493 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:41:55,210 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:42:08,608 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:42:24,842 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:42:38,698 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:45:26,421 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:45:53,682 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:46:02,870 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:58:42,373 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 21:58:44,076 ERROR: Exception on /index [GET] [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\main\routes.py", line 39, in index
    prev_url=prev_url)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 12, in block "body"
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\templates\base.html", line 31, in block "navbar"
    <li><a href="{{ url_for('auth.index') }}">{{ _('—¯Œ¾”Â') }}</a></li>
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.index'. Did you mean 'auth.login' instead?
2020-05-01 21:58:56,036 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
2020-05-01 22:00:34,888 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc-master\app\__init__.py:74]
